-- ============================================================
-- LUCASOL — Schéma Supabase complet
-- À exécuter dans l'éditeur SQL du dashboard Supabase
-- (SQL Editor → New query → coller → Run)
-- ============================================================


-- ============================================================
-- 1. TABLES
-- ============================================================

-- Avis clients
CREATE TABLE IF NOT EXISTS public.reviews (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client     TEXT    NOT NULL,
  rating     INTEGER NOT NULL DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  comment    TEXT    NOT NULL,
  date       TEXT    NOT NULL,
  source     TEXT    NOT NULL DEFAULT 'google' CHECK (source IN ('google', 'manual')),
  visible    BOOLEAN NOT NULL DEFAULT true,
  featured   BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Réalisations
CREATE TABLE IF NOT EXISTS public.realisations (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            TEXT    NOT NULL,
  category         TEXT    NOT NULL CHECK (category IN ('parquet','pvc','moquette','poncage','avant-apres')),
  image_url        TEXT    NOT NULL,
  before_image_url TEXT,
  after_image_url  TEXT,
  description      TEXT,
  published        BOOLEAN NOT NULL DEFAULT true,
  display_order    INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Demandes de contact
CREATE TABLE IF NOT EXISTS public.contact_requests (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL,
  phone      TEXT,
  message    TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','read','replied')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- 2. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.reviews          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.realisations     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- REVIEWS — lecture publique (visible=true seulement), tout pour les admins
CREATE POLICY "reviews_public_select" ON public.reviews
  FOR SELECT TO anon USING (visible = true);

CREATE POLICY "reviews_auth_all" ON public.reviews
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- REALISATIONS — lecture publique (published=true seulement), tout pour les admins
CREATE POLICY "realisations_public_select" ON public.realisations
  FOR SELECT TO anon USING (published = true);

CREATE POLICY "realisations_auth_all" ON public.realisations
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CONTACT REQUESTS — insertion publique, lecture/update pour les admins
CREATE POLICY "contact_requests_public_insert" ON public.contact_requests
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "contact_requests_auth_select" ON public.contact_requests
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "contact_requests_auth_update" ON public.contact_requests
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "contact_requests_auth_delete" ON public.contact_requests
  FOR DELETE TO authenticated USING (true);


-- ============================================================
-- 3. STORAGE BUCKETS
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('realisations', 'realisations', true, 10485760, ARRAY['image/jpeg','image/jpg','image/png','image/webp']),
  ('services',     'services',     true, 10485760, ARRAY['image/jpeg','image/jpg','image/png','image/webp']),
  ('hero',         'hero',         true, 10485760, ARRAY['image/jpeg','image/jpg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;

-- Lecture publique (incluse automatiquement via public=true)
-- Upload/suppression réservés aux admins
CREATE POLICY "storage_realisations_auth_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'realisations');

CREATE POLICY "storage_realisations_auth_update" ON storage.objects
  FOR UPDATE TO authenticated USING (bucket_id = 'realisations');

CREATE POLICY "storage_realisations_auth_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'realisations');

CREATE POLICY "storage_services_auth_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'services');

CREATE POLICY "storage_services_auth_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'services');

CREATE POLICY "storage_hero_auth_insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'hero');

CREATE POLICY "storage_hero_auth_delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'hero');


-- ============================================================
-- 4. SEED DATA — Avis clients réels
-- (les réalisations sont insérées par le script de migration)
-- ============================================================

INSERT INTO public.reviews (client, rating, comment, date, source, visible) VALUES
  ('Félix Werlé',        5, 'Restauration complète (ponçage/vitrification) de 90m² de parquet. Professionnalisme, détail et savoir-faire remarquables.',         'Janvier 2023',  'google', true),
  ('Anthony d''Ambra',   5, 'Prestation de pose en bâton rompu. Très satisfait du conseil, de la propreté et des finitions.',                                    'Janvier 2026',  'google', true),
  ('Michel Carrieri',    5, 'Travail de qualité et très professionnel. Recommande sans hésiter.',                                                                 'Mars 2026',     'google', true),
  ('Thomas Huck',        5, 'Travail de grande qualité, rien à redire. Recommande fortement.',                                                                    'Février 2026',  'google', true),
  ('Vincent Cordier',    5, 'Artisan de confiance, travail parfait et personnalité "au top".',                                                                    'Août 2025',     'google', true),
  ('Valerie Haegel',     5, 'Communication facile et rapide. Lucas est à l''écoute. Résultat magnifique pour les sols.',                                         'Août 2023',     'google', true),
  ('Olivia BOUILLON',    5, 'Très bons conseils pour une rénovation complète. Artisan consciencieux et attentif aux détails.',                                    'Août 2025',     'google', true),
  ('Olivia Ho',          5, 'Pose de parquet dans un appartement. Travail remarquable et bons conseils.',                                                         'Juin 2021',     'google', true),
  ('Olivia Pinto',       5, 'Travail très soigné pour la pose de parquet. Recommande vivement Lucas et son collègue.',                                           'Octobre 2024',  'google', true),
  ('Thibault Lemonnier', 5, 'Pose de parquet massif et stratifié. Tarifs raisonnables et résultat impeccable.',                                                  'Avril 2023',    'google', true),
  ('Serge Delacour',     5, 'Artisan passionné, professionnel et minutieux. Travail proche de la perfection.',                                                    'Avril 2021',    'google', true),
  ('Aline Martin',       5, 'Résultat impeccable, respect du devis et des délais. Très bon poseur.',                                                              'Mai 2021',      'google', true),
  ('Caroline Mary',      5, 'Travail minutieux et méticuleux. Enchantée du résultat.',                                                                            'Novembre 2023', 'google', true),
  ('Pierrick Rompillon', 5, 'Du conseil aux finitions, sérieux remarquable. Travail visible à SENSAS et RIVAL QUIZ à Mundolsheim.',                              'Mars 2026',     'google', true),
  ('Denis Sasorith',     5, 'Très bon artisan, recommande fortement.',                                                                                            'Mars 2026',     'google', true),
  ('Perrine Huck',       5, 'Réactivité, Ponctualité, Qualité, Professionnalisme, Prix — tout y est.',                                                           'Avril 2022',    'google', true);


-- ============================================================
-- INSTRUCTIONS APRÈS EXÉCUTION
-- ============================================================
-- 1. Dans Authentication > Users : créer le compte admin
--    (email + mot de passe que vous utiliserez pour vous connecter)
-- 2. Exécuter le script de migration des images :
--    node --env-file=.env.local scripts/migrate-to-supabase.mjs
-- ============================================================
